name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Clean
      run: dotnet clean -c Release
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload Release Build Artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: Release Build
        path: /home/runner/work/CommandLineParser.Core/CommandLineParser.Core/CommandLineParser/bin/Release/**/*
